name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/cnp2329.pem
          chmod 600 ~/.ssh/cnp2329.pem

      - name: Prepare package.json
        run: mv package.json.example package.json

      - name: Create .env file from GitHub Secret
        run: |
          echo "${{ secrets.REACT_ENV }}" > .env
          echo ".env file created successfully"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          CI=false NODE_OPTIONS="--max-old-space-size=4096" npm run build

      - name: Ensure target directory exists on EC2
        run: |
          ssh -i ~/.ssh/cnp2329.pem -o StrictHostKeyChecking=no -o IdentitiesOnly=yes \
          ubuntu@ec2-99-81-57-169.eu-west-1.compute.amazonaws.com "mkdir -p /var/www/html/Shot-call-Production"

      - name: Deploy build to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/cnp2329.pem -o StrictHostKeyChecking=no -o IdentitiesOnly=yes" \
          ./build/ ubuntu@ec2-99-81-57-169.eu-west-1.compute.amazonaws.com:/var/www/html/Shot-call-Production

      - name: Copy .env file to target
        run: |
          ssh -i ~/.ssh/cnp2329.pem -o StrictHostKeyChecking=no -o IdentitiesOnly=yes \
          ubuntu@ec2-99-81-57-169.eu-west-1.compute.amazonaws.com "echo '${{ secrets.REACT_ENV }}' > /var/www/html/Shot-call-Production/.env"

      - name: Restart app with PM2
        run: |
          ssh -i ~/.ssh/cnp2329.pem -o StrictHostKeyChecking=no -o IdentitiesOnly=yes \
          ubuntu@ec2-99-81-57-169.eu-west-1.compute.amazonaws.com "
            cd /var/www/html/Shot-call-Production && \
            /home/ubuntu/.nvm/versions/node/v16.13.0/bin/pm2 delete ShotCallApp || true && \
            /home/ubuntu/.nvm/versions/node/v16.13.0/bin/pm2 start npm --name ShotCallApp -- start && \
            /home/ubuntu/.nvm/versions/node/v16.13.0/bin/pm2 save
          "
