name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/prod.pem
          chmod 600 ~/.ssh/prod.pem

      - name: Fetch .env from Server
        run: |
          ssh -i ~/.ssh/prod.pem -o StrictHostKeyChecking=no -o IdentitiesOnly=yes ubuntu@${{ secrets.EC2_HOST }} "cat /home/ubuntu/env.txt" > .env

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy Code to EC2
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/prod.pem -o StrictHostKeyChecking=no -o IdentitiesOnly=yes" \
            ./ ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/Shot-call-Production \
            --exclude '.git' --exclude 'node_modules'

      - name: Restart Application with PM2
        run: |
          ssh -i ~/.ssh/prod.pem -o StrictHostKeyChecking=no -o IdentitiesOnly=yes ubuntu@${{ secrets.EC2_HOST }} \
            "cd /var/www/html/Shot-call-Production && pm2 restart all || pm2 start npm --name shotcall -- run start"
