name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/prod.pem
          chmod 600 ~/.ssh/prod.pem

      - name: Fetch .env from Server
        run: |
          ${{ secrets.EC2_SSH }} "cat /home/ubuntu/env.txt" > .env

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy Code to EC2
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/prod.pem -o StrictHostKeyChecking=no -o IdentitiesOnly=yes" \
            ./build/ ubuntu@ec2-99-81-57-169.eu-west-1.compute.amazonaws.com:/var/www/html/Shot-call-Production \
            --exclude '.git' --exclude 'node_modules'

      - name: Restart App with PM2
        run: |
          ${{ secrets.EC2_SSH }} "pm2 restart shotcall-frontend || pm2 start /var/www/html/Shot-call-Production/server.js --name shotcall-frontend"
